name: build for canary

on:
  push:
    branches: main
  schedule:
      - cron: '0 0 * * *'  
  repository_dispatch:  
    types: [canary]
jobs:
  build:
    runs-on: windows-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v4
      - name:  Download Rfu-desktop Windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            repo: 'czqu/rfu-desktop'
            version: 'tags/canary'
            file: "rfu_desktop_windows_x64.zip"
            token: ${{ secrets.GH_TOKEN }}
      - name:  Download RemoteFingerUnlock arm64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/canary'
          file: "RemoteFingerUnlockModule_ARM64.zip"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download RemoteFingerUnlock x86
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/canary'
          file: "RemoteFingerUnlockModule_Win32.zip"
          token: ${{ secrets.GH_TOKEN }} 
      - name:  Download RemoteFingerUnlock x64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/canary'
          file: "RemoteFingerUnlockModule_x64.zip"
          token: ${{ secrets.GH_TOKEN }}     

      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/canary'
          file: "core-service-x86.exe"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/canary'
          file: "core-service-x64.exe"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/canary'
          file: "core-service-arm64.exe"
          token: ${{ secrets.GH_TOKEN }}             
      - name:  Download install-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            repo: 'czqu/fadacontrol'
            version: 'tags/canary'
            file: "install-service-x64.exe"
            token: ${{ secrets.GH_TOKEN }}        
      - name:  Download install-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            repo: 'czqu/fadacontrol'
            version: 'tags/canary'
            file: "install-service-arm64.exe"
            token: ${{ secrets.GH_TOKEN }}     
      - name:  Download install-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
            repo: 'czqu/fadacontrol'
            version: 'tags/canary'
            file: "install-service-x86.exe"
            token: ${{ secrets.GH_TOKEN }}         
      - name: unzip
        run: |
           Get-ChildItem -Path . -Filter *.zip | ForEach-Object {
            $zipFileName = $_.BaseName
            $destinationPath = Join-Path -Path (Get-Location) -ChildPath $zipFileName
            Expand-Archive -Path $_.FullName -DestinationPath $destinationPath }
        shell: pwsh
      - run : ls
      - name: Compile x64 Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_x64.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9
      - name: Compile x86
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_x86.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9
      - name: Compile arm64
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_arm64.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9         


      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "Output/*.exe"
          prerelease: true
          tag_name:  canary
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md