name: nightly build

on:
  push:
  schedule:
      - cron: '0 0 * * *'  
 
jobs:
  build:
    runs-on: windows-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v4

      - name:  Download RemoteFingerUnlock arm64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/nightly'
          file: "RemoteFingerUnlockModule_ARM64.zip"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download RemoteFingerUnlock x86
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/nightly'
          file: "RemoteFingerUnlockModule_Win32.zip"
          token: ${{ secrets.GH_TOKEN }} 
      - name:  Download RemoteFingerUnlock x64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/RemoteFingerUnlockModule'
          version: 'tags/nightly'
          file: "RemoteFingerUnlockModule_x64.zip"
          token: ${{ secrets.GH_TOKEN }}     

      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/nightly'
          file: "core-service-x86.exe"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/nightly'
          file: "core-service-x64.exe"
          token: ${{ secrets.GH_TOKEN }}
      - name:  Download core-service
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'czqu/fadacontrol'
          version: 'tags/nightly'
          file: "core-service-arm64.exe"
          token: ${{ secrets.GH_TOKEN }}                    
      - name: unzip
        run: |
           Get-ChildItem -Path . -Filter *.zip | ForEach-Object {
            $zipFileName = $_.BaseName
            $destinationPath = Join-Path -Path (Get-Location) -ChildPath $zipFileName
            Expand-Archive -Path $_.FullName -DestinationPath $destinationPath }
        shell: pwsh
      - run : ls
      - name: Compile x64 Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_x64.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9
      - name: Compile x86
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_x86.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9
      - name: Compile arm64
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup_arm64.iss
          options: /O+  /DAppVersion=3.5.1.9 /DVersionInfoVersion=3.5.1.9         


      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "Output/*.exe"
          prerelease: true
          tag_name:  nightly
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md
